M48
; DRILL file {KiCad 7.0.5-4d25ed1034~172~ubuntu22.04.1} date sáb 17 jun 2023 18:54:08
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-17T18:54:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-4d25ed1034~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1122
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X7.68Y-1.945
X7.68Y-5.445
T2
X6.805Y-2.5025
T0
M30
