M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date sáb 20 may 2023 19:06:34
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-20T19:06:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1122
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X7.68Y-1.945
X7.68Y-5.445
T2
X6.805Y-2.5025
T0
M30
